apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychainhfdvalidator4ibft
  namespace: supplychainhfd-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychainhfdvalidator4ibft
  chart:
    git: ssh://git@github.com/azoumi/blockchain-automation-framework.git
    ref: demo/besu
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://900a2338c99a6e929fa587f246cbb5143476d95260702eb00fee59feb134eb2ded55ec7b4ad0a8d4d6ba39a8b3610a3e6b39c1e8f2a8eb0ed790a8949f26248d@54.74.240.232:15050"
      - "enode://752650340aeef4da502a54f751eaaef809e5e3996d9af431c64e30595c3f3c5539d7194a1b046291687cfb73755f4655e4674ddca922c0debfb472cd0a6c2695@54.74.240.232:15060"
      - "enode://fb612ace1ae025e3ea30c564d3dd31b72210c93cd2e7eb1a4ec6124ae3ff8ff1ecbf10ba4d0d3b027e56e70d3646f586457694f13b8bf3a5aafecc5975da8dd7@54.74.240.232:15070"
      - "enode://1ec1253a636f48b412a2922cab61f8548a14ed157ef3a647fb64fa7df6ffefb756aaa13275254baea6ee933318b5cd8c44ead2c6b63ff96a5674a3a87ce12fac@54.74.240.232:15080"
      - "enode://4b69ee9bf64322fe342ceb95797faf42a68bdfe52d6adc17d0bafa59adb43d61c7dbaf6f3a5a8f81d2369011572774f47b8e9d71d9f6646e6d7717170e1c5bd1@54.74.240.232:15010"
      - "enode://86028353ec96099b0be12d2d176caeb885a010b8c5c739294cda95302286ff1041b0a266488268b9058c38897e16caca30ff74ec5ba0b899b89cad7ee24e0acb@54.74.240.232:15020"
      - "enode://3ee322071f5bae692af16ac48222c7dd0191e7604888115d2637680e77e41d28cb1deb842c0a60b580ecfa82c28ee2fe1ec9d9f4a5ee6ab1bf61df6bdc11a344@54.74.240.232:15030"
      - "enode://4a44691d54a0133e08288fd522f0305f97165a81853e51d7d47bb85b72649b734df243d65be4d89eea3354f74a7fbc93bb921967e380a19cefacb0f09ee727c4@54.74.240.232:15040"

    metadata:
      namespace: supplychainhfd-bes
      labels:

    ambassador:
      external_url_suffix: bs.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false

    proxy:
      provider: ambassador
      external_url: supplychainhfd.bs.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15080
      rpc: 15081

    images:
      node: hyperledger/besu:1.4.4
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator4
      tls: True
      consensus: ibft
      mountPath: /etc/genesis
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/supplychainhfd-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychainhfd

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDFlNzM0ODNhMDIwZThiMWFiYjU5MDlhOWRjOTkwYzAzYjNiNGFjYzA5NGU0ZDNmYWI0NmZiM2YzOTNmMjM3MmVlOTVkZmQxYzY1NWE4NDI2Njk5NGU4MzYxNjE1ZTY0MjkwZjdkZTg2NmJiZDU3MGVkMjQ5NDU2NTQ5NjE5NGIwZTE3NzJiNjgwY2E1N2I2YzNiNzBlMGRlNDMwNTE3NDBlMzM2OTk4MDg0MDAwMDAwMDBjMCIKfQ==
