apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: signer
  annotations:
    flux.weave.works/automated: "false"
  namespace: cenmhfd-ent
spec:
  releaseName: signer
  chart:
    path: platforms/corda-ent/charts/signer
    git: ssh://git@github.com/azoumi/blockchain-automation-framework.git
    ref: bug910
  values:
    nodeName: signer
    metadata:
      namespace: cenmhfd-ent
    replicas: 1
    image:
      imagePullSecret: regcred
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
    storage:
      name: cenmsc
    dockerImageSigner:
      name: corda/enterprise-signer
      tag: 1.2-zulu-openjdk8u242
      pullPolicy: Always
    acceptLicense: YES
    vault:
      address: http://vault.internal.dev.aws.blockchaincloudpoc-develop.com:8081
      role: vault-role
      authpath: cordaentcenmhfd
      serviceaccountname: vault-auth
      certsecretprefix: secret/cenmhfd
    healthcheck:
      readinesscheckinterval: 10
      readinessthreshold: 15
    serviceSsh:
      port: 2222
      targetPort: 2222
      type: ClusterIP
    service:
      type: ClusterIP
      port: 20003
    volume:
      baseDir: /opt/corda
    shell:
      user: signer
      password: signerP
    idmanPublicIP: idman.rc.dev.aws.blockchaincloudpoc-develop.com
    idmanPort: 8443
    serviceLocations:
      identityManager:
        host: idman.cenmhfd-ent
        port: 5052
      networkMap:
        host: networkmap.cenmhfd-ent
        port: 5050
      revocation:
        port: 5053
    signers:
      CSR:
        schedule:
          interval: 1m
      CRL:
        schedule:
          interval: 1d
      NetworkMap:
        schedule:
          interval: 1m
      NetworkParameters:
        schedule:
          interval: 1m
    cordaJarMx: 1
    healthCheckNodePort: 0
    jarPath: bin
    configPath: etc
