apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: notaryhfd
  annotations:
    flux.weave.works/automated: "false"
  namespace: supplychainhfd-ns
spec:
  releaseName: notaryhfd
  chart:
    path: platforms/r3-corda/charts/notary
    git: ssh://git@github.com/azoumi/blockchain-automation-framework.git
    ref: bug/948-lintingfix
  values:
    nodeName: notaryhfd
    replicas: 1
    metadata:
      namespace: supplychainhfd-ns
    image:
      containerName: index.docker.io/hyperledgerlabs/corda:4.4-linuxkit
      initContainerName: index.docker.io/hyperledgerlabs/alpine-utils:1.0
      imagePullSecret: regcred
      privateCertificate: true
      doormanCertAlias: doormanhfd.rc.dev2.aws.blockchaincloudpoc-develop.com
      networkmapCertAlias: networkmaphfd.rc.dev2.aws.blockchaincloudpoc-develop.com
    nodeConf:
      p2p:
        url: notaryhfd.supplychainhfd-ns
        port: 10002
      ambassadorAddress: notaryhfd.rc.dev2.aws.blockchaincloudpoc-develop.com:10010
      rpcSettings:
        useSsl: false
        standAloneBroker: false
        address: "0.0.0.0:10003"
        adminAddress: "0.0.0.0:10005"
        ssl:
          certificatesDirectory: na-ssl-false
          sslKeystorePath: na-ssl-false
          trustStoreFilePath: na-ssl-false
      legalName: O=Notary,OU=Notary,L=London,C=GB #use peer-node level subject for legalName
      messagingServerAddress:
      jvmArgs:
      systemProperties:
      sshd:
        port:
      exportJMXTo:
      transactionCacheSizeMegaBytes: 8
      attachmentContentCacheSizeMegaBytes: 10
      attachmentCacheBound: 1024
            
      notary:
        validating: false
       
      detectPublicIp: false
      database:
        transactionIsolationLevel: READ_COMMITTED
        exportHibernateJMXStatistics: false
      dbUrl: notaryhfddb
      dbPort: 9101
      dataSourceClassName: "org.h2.jdbcx.JdbcDataSource"
      dataSourceUrl: "jdbc:h2:tcp://notaryhfddb:9101/persistence;DB_CLOSE_ON_EXIT=FALSE;LOCK_TIMEOUT=10000;WRITE_DELAY=100;AUTO_RECONNECT=TRUE;"
      jarPath: "/data/corda-workspace/h2/bin"
      networkMapURL: https://networkmaphfd.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
      doormanURL: https://doormanhfd.rc.dev2.aws.blockchaincloudpoc-develop.com:8443
      compatibilityZoneURL:
      jarVersion: 4.4
      devMode: false
      env:
        - name: JAVA_OPTIONS
          value: -Xmx512m
        - name: CORDA_HOME
          value: /opt/corda
        - name: BASE_DIR
          value: /base/corda
    credentials:
      dataSourceUser: sa
      rpcUser:
        - name: notaryhfdoperations
          permissions: [ALL]

    cordapps:
      getcordapps: false

    volume:
      baseDir: /base/corda
    resources:
      limits: "1Gi"
      requests: "1Gi" 
    pvc:
      name: notaryhfd-pvc
      annotations: {}
      memory: 512Mi
      storageClassName: awsstorageclass

    service:
      name: notaryhfd
      type: ClusterIP
      p2p:
        port: 10002
        targetPort: 10002
      rpc:
        port: 10003
        targetPort: 10003 
      rpcadmin:
        port: 10005
        targetPort: 10005
         
    deployment:
      annotations: {}
    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      role: vault-role
      authpath: cordanotaryhfd
      serviceaccountname: vault-auth
      dbsecretprefix: notaryhfd/credentials/database
      rpcusersecretprefix: notaryhfd/credentials/rpcusers
      tokensecretprefix: notaryhfd/credentials/vaultroottoken
      keystoresecretprefix: notaryhfd/credentials/keystore
      certsecretprefix: notaryhfd/certs
      networkmapsecretprefix: notaryhfd/credentials/networkmappassword
      cordappsreposecretprefix: notaryhfd/credentials/cordapps

          
    healthcheck:
      readinesscheckinterval: 20
      readinessthreshold: 20
    ambassador:
      component_name: notaryhfd
      external_url_suffix: rc.dev2.aws.blockchaincloudpoc-develop.com
      p2p_ambassador: 10010
      
