apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: supplychaincompanyvalidator4ibft
  namespace: supplychaincompany-bes
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: supplychaincompanyvalidator4ibft
  chart:
    git: ssh://git@github.com/azoumi/blockchain-automation-framework.git
    ref: demo/besu
    path: platforms/hyperledger-besu/charts/node_validator 
  values:
    replicaCount: 1

    healthcheck:
      readinessthreshold: 100
      readinesscheckinterval: 5

    staticnodes:
      - "enode://2bf53ce56d7faaced75d543dbba88a960ef88f3dbf14506b2135198730f0ecf178b434cdb77fcc6e29536d4f88fe10202d64336333e916fe6c2c88fcff0f7b03@54.171.205.179:15050"
      - "enode://59511e9cf715f41b0a7ca1ed45b8f3bdecbdfb51e059fb72402a0debb0974be7998635f204b740e960acf84835b310f46f46e234476155fb1ff3cd8afe06de4c@54.171.205.179:15060"
      - "enode://195365c6a6ffc6ee347583a8c94c85f5c9c5ac8dc2351f9e62210a48a785979912b55cd2852ba202b57cb189071ecb99e2bcca2db01e0216808597ab1864bb7d@54.171.205.179:15070"
      - "enode://50071b275842ff95c2c318746751bc8a52ef07758ef36597b22e9ae6861fee24a30c5733e9815af4797c6a31a30af8075baee707cd299f8c5533d40e588a601b@54.171.205.179:15080"
      - "enode://09b0331a99014b9deff38a3e02017711044ea71471e38dccf142423e0ec77e9f8760d0d376385c21b2594e3d1dc021a7b126a4c93cfb09c8349e525442479f7b@54.171.205.179:15010"
      - "enode://223e478997d30cedd1d3aba636ddb295d71987f9553a9be009fd965a4f1e0b3edea0ffe201b3700216c2357e2d1a2cf5736941bca1a2114c3f2268e3f6b16002@54.171.205.179:15020"
      - "enode://672a4f78d18e90e55bcb32fb350a8988558da5202b1b74eb893ca909f02ff416170dd40605eea8f1a9e4dae4be2183b4681f55f9a21ac9430c7daef65bf80ee0@54.171.205.179:15030"
      - "enode://4f589685e6eaf4b6b996ac0db0af774216b5016f26424f5ed2f74c4d1db147f7f585691a494541300099458457a6190706da74f264bebf611b968f6f9a3ca507@54.171.205.179:15040"

    metadata:
      namespace: supplychaincompany-bes
      labels:

    ambassador:
      external_url_suffix: bs.dev2.aws.blockchaincloudpoc-develop.com

    liveliness_check:
      enabled: false

    proxy:
      provider: ambassador
      external_url: supplychaincompany.bs.dev2.aws.blockchaincloudpoc-develop.com
      p2p: 15080
      rpc: 15081

    images:
      node: hyperledger/besu:1.4.4
      alpineutils: hyperledgerlabs/alpine-utils:1.0

    node:
      name: validator4
      tls: True
      consensus: ibft
      mountPath: /etc/genesis
      servicetype: ClusterIP
      imagePullSecret: regcred
      ports:
        p2p: 30303
        rpc: 8545
        ws: 8546

    storage:
      storageclassname: awsstorageclass
      storagesize: 1Gi

    vault:
      address: http://vault.internal.dev2.aws.blockchaincloudpoc-develop.com:20001
      secretprefix: secret/supplychaincompany-bes/crypto/validator4
      serviceaccountname: vault-auth
      keyname: data
      tlsdir: tls
      role: vault-role
      authpath: besusupplychaincompany

    genesis: ewogICJjb25maWciOiB7CiAgICAiY2hhaW5JZCI6IDIwMTgsCiAgICAiY29uc3RhbnRpbm9wbGVmaXhibG9jayI6IDAsCiAgICAiY29udHJhY3RTaXplTGltaXQiOiAyMTQ3NDgzNjQ3LAogICAgImliZnQyIjogewogICAgICAiYmxvY2twZXJpb2RzZWNvbmRzIjogMiwKICAgICAgImVwb2NobGVuZ3RoIjogMzAwMDAsCiAgICAgICJyZXF1ZXN0dGltZW91dHNlY29uZHMiOiAxMAogICAgfQogIH0sCiAgIm5vbmNlIjogIjB4MCIsCiAgInRpbWVzdGFtcCI6ICIweDU4ZWU0MGJhIiwKICAiZ2FzTGltaXQiOiAiMHgxZmZmZmZmZmZmZmZmZiIsCiAgImRpZmZpY3VsdHkiOiAiMHgxIiwKICAiZXh0cmFEYXRhIjogIjB4Zjg3ZWEwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMDAwMGY4NTQ5NDcxZTJkMTBjZmYxNjQyZDEyMDAwNWZjNDhmZDY1NWVhZjY2YzQ5NTU5NDI4ZmUyZTE2MmI5ZTM0YjBmM2NjOGFjNTM0YmM2YWE3ZGUyMWJhZWQ5NDhkMmYxOTcyZDRlNmM0ZmI0MWM1NGU4NTcxNzFkZWViYzM0MzM5OTY5NGFiNDE2N2EwYzhiYTJjZjY2NmZiMmYxNDQ2MDY4ZjMzMWUwZDQ3MjQ4MDg0MDAwMDAwMDBjMCIKfQ==
